### ISSUE TITLE
what does 'ENV container=docker' mean?

### ISSUE THREAD

**Issue by gerontius** [geerlingguy/docker-centos7-ansible#11]
I saw this is also in the centos systemd instructions but Im not sure what it actually does?

**Comment by geerlingguy** [comment]
@gerontius honestly that's why I put it in there, I have no clue why it's in the recommendation but maybe there's some deep dark code in the centos image that uses it somehow... or some random developer of days past added it for their own purposes and now it's part of the docs forever :D

I'm leaving it, because if it ain't broke... ;-)
